<?php
/**
 * Freshcodes
 *
 * It is also available through the world-wide-web at this URL:
 * http://freshcodes.in
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Freshcodes does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Freshcodes does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Freshcodes
 * @package     Freshcodes_Fastorder
 * @version     0.1.0
 * @author      Freshcodes Team <developers@freshcodes.in>
 *
 */
$id = $this->getRequest()->getParam('id', null);
$model = Mage::getModel("fastorder/fastorderdetails")->load($id);
//echo $model->getFastorderId();
//echo $model->getCreatedDate();
$orderStoreDate = $this->formatDate($model->getCreatedDate(), 'medium', true);
$c_status = $model->getStatus();
//print_r($model);exit;
$status = Freshcodes_Fastorder_Block_Adminhtml_Fastorderdetails_Grid::getValueArray5();

?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">Fastorder Details</h4>
    </div>
    <div class="fieldset fieldset-wide">
        <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
				 <tr>
                    <td class="label">
                        <label for="multilocationinventory_global_inventory">Order Date</label>
                    </td>
                    <td class="value">
                        <span class="bold"><?php echo $orderStoreDate; ?></span>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="multilocationinventory_global_inventory">Customer Name</label>
                    </td>
                    <td class="value">
                        <span class="bold"><?php echo $model->getName() ?></span>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="multilocationinventory_global_location">Email</label>
                    </td>
                    <td class="value">
                        <span class="bold"><?php echo $model->getEmail() ?></span>
                    </td>
                </tr>
				<tr>
                    <td class="label">
                        <label for="multilocationinventory_global_location">Phone</label>
                    </td>
                    <td class="value">
                        <span class="bold"><?php echo $model->getPhone() ?></span>
                    </td>
                </tr>
				<tr>
                    <td class="label">
                        <label for="multilocationinventory_global_location">Status</label>
                    </td>
                    <td class="value">
                        <select id="status" name="status" class=" select">
							<?php
								foreach($status as $key=>$value)
								{
							?>
									<option value="<?php echo $value['label']; ?>" <?php if($c_status == $value['label']) { echo "selected";} ?>><?php echo $value['label']; ?></option>
							<?php
								}
							?>
							
						</select>
                    </td>
                </tr>
            </table>
        </div>
        <div>&nbsp;</div>
        <div>&nbsp;</div>
        <div class="grid">
			<div class="entry-edit">
				<div class="entry-edit-head">
					<h4 class="icon-head head-products">Items Ordered</h4>
				</div>
			</div>
            <table cellspacing="0" class="data order-tables">
                <thead>
                <tr class="headings">
                    <th>Name</th>
                    <th>Price</th>
                    <th>QTY</th>
					<th>SUBTOTAL</th>
					<th>DISCOUNT</th>
					<th>ROW TOTAL</th>
                </tr>
                </thead>
                
				<?php
				$modelProduct  = Mage::getModel("fastorder/fastorderproduct")->getCollection()->addFieldToFilter('fastorder_id',$id );
				$count = 2;
				//print_r($modelProduct->getData('product_sku'));
				
				//print_r($modelProduct->getData()->getSku());
				?>
				<?php foreach ($modelProduct as $product): ?>
					<?php
					$modelproductoption = Mage::getModel("fastorder/fastorderproductoption")->getCollection()->addFieldToFilter('productdetails_id',$product['id']);
					//print_r($modelproductoption->getData());
					?>
					<tbody class="<?php if($count % 2 == 0){ echo "even"; } ?>">
                    <tr class="border">
                        <td>
                            <?php echo $product['product_name']; ?>
							<?php
							echo "</br><strong>Sku</strong> : ".$product['product_sku'];
							foreach ($modelproductoption as $productoption)	
							{
								echo "</br><strong>".$productoption['label']."</strong> : ".$productoption['value'];
							}
							?>
                        </td>
                        <td>
                            <?php echo Mage::helper('core')->currency($product['product_price'], true, false); ?>
                        </td>
                        <td>
                            <?php echo $product['qty']; ?>
                        </td>
                        <td class="">
							<?php $totalPrice = $product['product_price']; ?>
							<?php $final_price = $totalPrice*$product['qty']; ?>
							<?php echo Mage::helper('core')->currency($final_price, true, false); ?>
                        </td>
						<td class="">
							<?php $discountPrice = $product['product_discount']; ?>
							<?php echo Mage::helper('core')->currency($discountPrice, true, false); ?>
                        </td>
						<td class="last">
							<?php $mainPrice = $final_price - $discountPrice; ?>
							<?php echo Mage::helper('core')->currency($mainPrice, true, false); ?>
                        </td>
                       
                    </tr>
					</tbody>
                <?php $count++; endforeach; ?>
                
            </table>
			
        </div>
    </div>
</div>

<script type="text/javascript">
$$('.demac_multilocationinventory_manage_stock').each(function(element) {
  element.observe('change', function (ev) {
    var visibility_str = "hidden";
    if(ev.target.value == "1") {
      visibility_str = "visible";
    }
    ev.target.parentElement.parentElement.select('input, select').each(function(toggleElement) {
      if(!toggleElement.hasClassName('demac_multilocationinventory_manage_stock')) {
        toggleElement.setStyle({visibility: visibility_str});
      }
    });
  });
});
</script>
