<?php
/**
 * Freshcodes
 *
 * It is also available through the world-wide-web at this URL:
 * http://freshcodes.in
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Freshcodes does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Freshcodes does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Freshcodes
 * @package     Karon_Fastorder
 * @version     0.1.0
 * @author      Freshcodes Team <developers@freshcodes.in>
 *
 */
$cart = Mage::getModel('checkout/cart')->getQuote();
?>
<table cellspacing="0" cellpadding="0" border="0" height="100%" width="100%">
        <tr>
            <td align="center" valign="top" style="padding:20px 0 20px 0">
                <!-- [ header starts here] -->
                <table bgcolor="FFFFFF" cellspacing="0" cellpadding="10" border="0" width="650" style="border:1px solid #E0E0E0;">
				<tr style="background:#f1f1f1;">
					<td style="font-weight:bold">Product Name</td>
					<td style="font-weight:bold">Quantity</td>
					<td style="font-weight:bold">Total Price</td>
				</tr>
				<?php
					$i = 1;
					foreach ($cart->getAllItems() as $item) {
					?>
					<tr style="<?php if($i % 2 == 0): echo "background:#ddd;"; endif; ?>">
					<td><?php echo $item->getProduct()->getName(); ?></td>
					<td><?php echo $item->getQty(); ?></td>
					<td><?php echo Mage::helper('core')->currency($item->getRowTotal(), true, false); ?></td>
					</tr>
					<?php
					}
				?>
				</table>
			</td>
		</tr>
</table>