<?php
/**
 * Freshcodes
 *
 * It is also available through the world-wide-web at this URL:
 * http://freshcodes.in
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Freshcodes does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Freshcodes does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Freshcodes
 * @package     Karon_Fastorder
 * @version     0.1.0
 * @author      Freshcodes Team <developers@freshcodes.in>
 *
 */
if($this->getActive()):
?>
<div class="fastorder-block">
<div class="fastorder-inner">
<form id="fastorder-form" action="<?php echo $this->getUrl('fastorder/index/post') ?>" method="post" class="fastorder-form">
<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
        <h2><?php echo Mage::helper('contacts')->__($this->getTitle()); ?></h2>
            <div class="field-wrapper">
				<?php if($this->enableName()): ?>
				<input class="input-text required-entry " type="text" id="name" name="name" value="" placeholder="Name">
				<?php endif; ?>
				<input class="input-text required-entry  validate-email" type="text" id="email" name="email" value="" placeholder="Email">
				<?php if($this->enablePhone()): ?>
				<input class="input-text required-entry " type="text" id="phone" name="phone" value="" placeholder="Phone">
				<?php endif; ?>
				<?php if($this->enableComment()): ?>
				<textarea name="comment" id="comment" placeholder="Comment"></textarea>
				<?php endif; ?>
                <div class="button-wrapper">
                   <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Submit')) ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Process To Fastorder') ?></span></span></button>
                </div>
            </div>
</form>
</div>
</div>
<?php
endif;
?>
<script type="text/javascript">
//<![CDATA[
    var fastorder = new VarienForm('fastorder-form', true);
//]]>
</script>
